### ISSUE TITLE
这个只能一个一个查题~

### ISSUE THREAD

**Issue by chenshiforever** [BA-NANA/zhihuishu-answer#1]
不如做个循环，直接抓所有的questionId+answerid，然后遍历一下就出了所有答案

**Comment by cszmzh** [comment]
> 不如做个循环，直接抓所有的questionId+answerid，然后遍历一下就出了所有答案

这是个不错的建议，但是这需要手动复制页面的HTML到python中进行抓取解析，因为刷新一次页面questionId的次序会变化，如果是在python中直接获取HTML答案顺序是不对的。等开学了我可以按上述思路进行改进~

**Comment by chenshiforever** [comment]
提供一个思路，就是直接在页面上运行，用js来写这样的话，通过dom元素来获取你需要的参数，就能直接获取到对应题目的答案，答案是图片的ABCD，但是ABCD的base64图片码的组合一共也就几十种，把它采集出来，就能对比出来把图片A转换为字符A，然后获取到答案的内容，把答案附到题目的旁边（或者直接模拟点击，真正实现一键完成），emm，哈哈，这个想法还是很有实现价值的。

**Comment by cszmzh** [comment]
> 提供一个思路，就是直接在页面上运行，用js来写这样的话，通过dom元素来获取你需要的参数，就能直接获取到对应题目的答案，~答案是图片的ABCD，但是ABCD的base64图片码的组合一共也就几十种~刚发现你有更好的实现方法，~把它采集出来，就能对比出来把图片A转换为字符A~然后获取到答案的内容，把答案附到题目的旁边（或者直接模拟点击，真正实现一键完成），emm，哈哈，这个想法还是很有实现价值的。

是的，用JavaScript来实现后查答案会更方便
